<a href="https://colab.research.google.com/github/satyamnewale/numpy-Book/blob/main/day_2-15Nov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day 2 - 15 nov

difference between dot and @
1. dot is applied to vector-vector, vector-matrix, matrix-matrix.
2. @ can also be doen with all.
3. dot choose behavior depending on shape (special case)
4. @ follows (mXn)@(nXp) and gives (mXp)
5. in dot vector-vector gives scalar
6. edge case :- in (1X3)(3X1) matrix output is matrix of(1X1) but numpy    convert it to scalar value and consider it as dot product.

---
1D array in matmul

---


1. (n,) @ (n,)	:      allowed	     -     (1×n) @ (n×1) converted to row and col vector




2. (n,) @ (n,k):	   NOT allowed    -  	no valid way




3. (n,m) @ (m,):	   NOT allowed	    -  no valid way



4. (n,) @ (n,1)	:   allowed	   -       (1×n) @ (n×1)  converted to row vector




5. (n,1) @ (n,)	:   NOT allowed	   -    becomes (n×1) @ (nx1) converted to col vector → outer product not satisdy  (mXn)@(nXp)





6. (n,) @ (1,n)	:   NOT allowed	   -    becomes (1xn) @ (1xn) converted to row vector → outer product not satisfy  (mXn)@(nXp)


---
1. rule: if value is at left side the (n,) -> (1,n)
2. rule: if value is at right side the (n,) -> (n,1)


---
element wise multiplication vs (dot and @)
1. in element wise only element and scalar value are multiplied, the shape is same.
2. in dot and @ elements are multiplied and then added, shape is reduced to scalar.
---

cosine similarity and angle:

1. +1 → perfectly same direction
2. 0 → 90° apart → perpendicular → no similarity
3. –1 → opposite direction

angle:

1. 0° → identical direction
2. Small angle (<30°) → very similar
3. 90° → unrelated
4. greater than 120° → mostly opposite
5. 180° → exactly opposite direction

---

multiplication rules:
1. always check inner dimensions ,they should be same (mxn)@(nxp).
2. outer shape should be (mxp).
3. Row of A interact with column of B.
4. not commutative : (mxn) != (nxm).
5. identity rule: I x A(nxm) = A.
---

broadcasting:
1. compare shape from right to left, last dim are equal. eg: (5,3) and (4,3) accepted.
2. they must be equal or one must be 1. eg:- (4,1) and (4,3) accepted, because 1 stretchs to 4.
3, missing dimensions is treaded as 1. eg:- (3,) and (2,3) accepted, (3,) treated as (1,3) row vector.
eg: (3,) + (2,) cannot broadcast.
eg: (2,3) - (3,) not accepted as convert to (3,1) due to left side as it becomes col vector and dont match value from right to left.
----
Vectorization is faster because NumPy executes operations in optimized C code using SIMD on contiguous memory, avoiding Python’s slow per-iteration overhead.

---

In [48]:
import numpy as np

arr = np.array([[1,2],[2,4],[4,8]])
print(f"array : {arr}")

#vector maths:
#element-wise:-
arr_add = arr + 5 # expected [[6,7],[7,9],[9,13]]
print(f"addition :{arr_add}")

arr_sub = arr - 3
print(f"subtraction : {arr_sub}")

arr_mul = arr * 2
print(f"multiplication : {arr_mul}")

arr_div = arr / 2 #scalar multiplication element wise
print(f"division : {arr_div}")

arr_vect1 = np.array([5,2,1])
arr_vect2 = np.array([1,2,3])

print(f"addition of vectors : {arr_vect1+arr_vect2}")
print(f"subtraction of vectors : {arr_vect1-arr_vect2}")
print(f"division of vectors : {(arr_vect1/arr_vect2).astype(np.int32)}")
print(f"multiplication of vectors : {arr_vect1*arr_vect2}")

#dot product and @
arr1 = np.array([[1,2,3]])
arr2 = np.array([[1],[2],[3]])
arr_vect = np.array([1,2,3])

print(f"shape of arr1:{arr1.shape}, dim:{arr1.ndim}")
print(f"shape of arr2:{arr2.shape}, dim:{arr2.ndim}")
print(f"shape of arr_vect:{arr_vect.shape}, dim:{arr_vect.ndim}")

#dot product
print(f"dot product : {np.dot(arr1,arr2)}, dim {np.dot(arr1,arr2).ndim}, shape:{np.dot(arr1,arr2).shape}")
print(f"@ product : {arr2@arr1}, dim {(arr2@arr1).ndim}, shape:{(arr2@arr1).shape}")
print(f"dot product of vector and matrix: {np.dot(arr_vect,arr2)}, dim {np.dot(arr_vect,arr2).ndim}, shape:{np.dot(arr_vect,arr2).shape}, gives scalar value.")
print(f"@ product of vector and matrix: {arr_vect@arr2},dim {(arr_vect@arr2).ndim}, shape:{(arr_vect@arr2).shape}, A 1D vector behaves like a row vector during @ (matmul) as it is at left side .NumPy automatically upgrades (3,) into (1,3) for matrix multiplication.")
print(f"@ product of vector and matrix: {arr1@arr_vect},dim {(arr1@arr_vect).ndim}, shape:{(arr1@arr_vect).shape}, A 1D vector behaves like a rcol vector during @ (matmul) as it is at right side .NumPy automatically upgrades (3,) into (3,1) for matrix multiplication.")

try:
  print(f"@ product of vector and matrix: {arr_vect@arr1},dim {(arr_vect@arr1).ndim}, shape:{(arr_vect@arr1).shape}")
except:
  print("@ product of vector and matrix: {arr_vect@arr1} ,A 1D vector behaves like a row vector during @ (matmul) as it is at left side .NumPy automatically upgrades (3,) into (1,3) for matrix multiplication but the dimensions dont satisfy (mXn)@(nXp) rule.")

try:
  print(f"@ product of vector and matrix: {arr2@arr_vect},dim {(arr2@arr_vect).ndim}, shape:{(arr2@arr_vect).shape}")
except:
  print("@ product of vector and matrix: {arr2@arr_vect} ,A 1D vector behaves like a col vector during @ (matmul) as it is at right side .NumPy automatically upgrades (3,) into (3,1) for matrix multiplication but the dimensions dont satisfy (mXn)@(nXp) rule.")

print(f"dot product : {np.dot(arr1,arr_vect)}, dim {np.dot(arr1,arr_vect).ndim}, shape:{np.dot(arr1,arr_vect).shape}")

try:
  print(f"dot product : {np.dot(arr2,arr_vect)}, dim {np.dot(arr2,arr_vect).ndim}, shape:{np.dot(arr2,arr_vect).shape}")
except:
  print("dot product : {np.dot(arr2,arr_vect)} dont satisfy rule ((mxn) dot (nxp))")
print("-----------------------------------------------------------------------------")

#slicing col and row wise
print("slicing :")

arr2D = np.array([[1,2,3,4],[5,6,7,8],[2,4,6,8],[1,3,5,7]])

print(f"row slicing : {arr2D[0:2,:]}")
print(f"col slicing : {arr2D[:,1:3]}")
print(f"row and col slicing : {arr2D[1:3,2:4]}")
print("-----------------------------------------------------------------------------")

print("transpose :")
array1 = np.array([[1,2,3],[1,4,7]])
array2 = np.array([[1,2,3]])
array3 = np.array([[1,2,3],[1,4,7],[3,4,5],[4,5,8]])
print(f"array1 : {array1}, shape of array1: {array1.shape}, array2: {array2}, shape of array2: {array2.shape}, array3: {array3}, shape of array3: {array3.shape}")
print(f"transpose of array1: {array1.T}, shape of T array1: {(array1.T).shape}, T of array2: {array2.T}, shape of T array2: {(array2.T).shape}, T of array3: {array3.T}, shape of T array3: {(array3.T).shape}")
print("transpose means to switch its rows to columns and columns to rows.")
print("-----------------------------------------------------------------------------")

print("norms , distance between vectors, cosine similarity and angle")
# there are three types of norms (Euclidean is mostly used)
# L2(euclidean norm = √(x₁² + x₂² + x₃² + …))
# L1(|x₁| + |x₂| + |x₃| + …)
# L∞(max(|x₁|, |x₂|, |x₃|, …))

arr_1 = np.array([3, 2,-4])
arr_2 = np.array([4, 0,-1])

#L2 manually calculate
L2_manual = (3**2 + 2**2 + (-4)**2)**0.5
print(f"L2 manually calculate : {L2_manual}, this is distance of vector from origin.")

#L2 with method
L2_linalg = np.linalg.norm(arr_1)
print(f"L2 with method : {L2_linalg}")

L1_manual = abs(3) + abs(2) + abs(-4)
print(f"L1 manually calculate : {L1_manual}")

L1_linalg = np.linalg.norm(arr_1,1)
print(f"L1 with method : {L1_linalg}")

L3_manual = max(abs(3),abs(2),abs(-4))
print(f"L3 manually calculate : {L3_manual}")

L3_linalg = np.linalg.norm(arr_1,np.inf)
print(f"L3 with method : {L3_linalg}")

# distance between vector
#formula ||v1-v2|| manually and with numpy method
dist_manual = ((3-4)**2 + (2-0)**2 + (-4-(-1))**2)**0.5
print(f"distance between vector manually : {dist_manual}")

dist_linalg = np.linalg.norm(arr_1-arr_2)
print(f"distance between vector with method : {dist_linalg}")

#cosine similarity manually and with methods
cosine_manual = (3*4 + 2*0 + (-4)*(-1))/((3**2 + 2**2 + (-4)**2)**0.5 * (4**2 + 0 +(-1)**2)**0.5)
print(f"cosine similarity manually : {cosine_manual}")

cosine_linalg = np.dot(arr_1,arr_2)/(np.linalg.norm(arr_1)*np.linalg.norm(arr_2))
print(f"cosine similarity with method : {cosine_linalg}")
print("as cosine similarity is 0.72 which is near 1 means the vectors are in acute angle")

angle = np.degrees(np.arccos(cosine_linalg))
print(f"angle between vectors : {angle}, the angle is 44 degree so it very similar.")

#broadcasting:
vect1=np.array([1,2,3])
matrix = np.array([[1,2,3],[5,6,7],[2,4,6],[1,3,5]])

matrix2 = np.array([[2],[3],[4],[5]])

print(f"vector:{vect1}, shape:{vect1.shape}")
print(f"matrix:{matrix}, shape:{matrix.shape}")
print(f"matrix-2:{matrix2}, shape:{matrix2.shape}")

print(f"vector + matrix:{vect1+matrix},shape :{(vect1+matrix).shape}, here the vector became (1x3) by row and 1 stretched to 4.")
print(f"matrix - matrix:{matrix2-matrix},shape :{(matrix2-matrix).shape}, here the value 4 match so broadcast is possible and 1 stretched to 3.")

#inlegal broadcasting
try:
  print(f"matrix - vector:{matrix-(matrix2.T)}")
except:
  print("matrix - vector:{matrix-(matrix2.T)}, not possible because matrix is (4x3) and matrix2.T is (1x4) due to this no value matches.")

try:
  print(f"vector - vector:{np.array([1,2,3])+np.array([4,5])}")
except:
  print("vector - vector:{[1,2,3]+[4,5]}, not possible because [1,2,3] is (3,) and [4,5] is (2,) even if convert to row and col vector its not possible as it becomes (1x3) and (2,1) no value matches.")

#adding scalar to matrix
print(f"matrix + scalar : {matrix+3}, shape{(matrix+3).shape}")

#masking:
print("----------------------------------------------------")
print("masking:")

mat = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])
mask = (mat%2 == 0)
even_arr = mat[mask]
print(f"original:{mat}, even value array: {even_arr}")
print(f"original:{mat}, multiple of 2 and 3:{mat[(mat%2 == 0) | (mat%3 == 0)]}")
print(f"original:{mat}, multiple of 2 and not multiple of 3:{mat[~(mat%2 != 0) & ~(mat%3 == 0)]}")
mat2D = np.array([[1,2,3,4,5],[2,4,6,8,10]])
row_mask = (mat2D.sum(axis=1)>4)
filtered_row = mat2D[row_mask]
print(f"original:{mat}, 2D matrix row operation:{filtered_row}")

col_mask = mat2D.mean(axis=0) < 2
filtered_cols = mat2D[:, col_mask]
print(f"original:{mat}, 2D matrix col operation:{filtered_cols}")

#modifing value:
mat[mat%3==0]=-1
print(f"modified matrix:{mat}")
print("----------------------------------------------------")

array : [[1 2]
 [2 4]
 [4 8]]
addition :[[ 6  7]
 [ 7  9]
 [ 9 13]]
subtraction : [[-2 -1]
 [-1  1]
 [ 1  5]]
multiplication : [[ 2  4]
 [ 4  8]
 [ 8 16]]
division : [[0.5 1. ]
 [1.  2. ]
 [2.  4. ]]
addition of vectors : [6 4 4]
subtraction of vectors : [ 4  0 -2]
division of vectors : [5 1 0]
multiplication of vectors : [5 4 3]
shape of arr1:(1, 3), dim:2
shape of arr2:(3, 1), dim:2
shape of arr_vect:(3,), dim:1
dot product : [[14]], dim 2, shape:(1, 1)
@ product : [[1 2 3]
 [2 4 6]
 [3 6 9]], dim 2, shape:(3, 3)
dot product of vector and matrix: [14], dim 1, shape:(1,), gives scalar value.
@ product of vector and matrix: [14],dim 1, shape:(1,), A 1D vector behaves like a row vector during @ (matmul) as it is at left side .NumPy automatically upgrades (3,) into (1,3) for matrix multiplication.
@ product of vector and matrix: [14],dim 1, shape:(1,), A 1D vector behaves like a rcol vector during @ (matmul) as it is at right side .NumPy automatically upgrades (3,) into (3,1) for matrix 

matrix_dot_add without loops

In [ ]:
import numpy as np

def dot_add(matrix_list, mat3, flag):
    # Check input
    if len(matrix_list) != 2:
        return "Error: matrix_list must contain exactly two matrices."

    try:
        mat1, mat2 = matrix_list

        # --- Check dot compatibility ---
        if mat1.shape[1] != mat2.shape[0]:
            if flag.lower() == "flex":
                # Try reshaping flexibly
                try:
                    mat2 = mat2.reshape(mat1.shape[1], -1)
                except ValueError:
                    return "Size of matrix is not compatible for dot product."
            else:
                return "Size of matrix is not compatible for dot product."

        # Perform dot product
        dot_product = np.dot(mat1, mat2)

        # --- Addition compatibility ---
        if dot_product.shape != mat3.shape:
            if flag.lower() == "flex":
                try:
                    # Try to broadcast safely
                    broadcast_shape = np.broadcast_shapes(dot_product.shape, mat3.shape)
                    mat3_b = np.broadcast_to(mat3, broadcast_shape)
                    dot_b = np.broadcast_to(dot_product, broadcast_shape)
                    return dot_b + mat3_b
                except ValueError:
                    return "Size of matrix is not compatible for addition."
            else:
                return "Size of matrix is not compatible for addition."
        else:
            return dot_product + mat3

    except ValueError as e:
        return f"Error: {e}"


# Example 1
mat1 = np.array([[1, 2], [3, 4], [5, 6]])
mat2 = np.array([[7, 8, 9], [10, 11, 12]])
mat3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(dot_add([mat1, mat2], mat3, flag="flex"))

# Example 2
mat_1 = np.array([[1, 2, 3], [4, 5, 6]])
mat_2 = np.array([[7, 8], [9, 10], [11, 12]])
mat_3 = np.array([[1, 2], [3, 4]])
print(dot_add([mat_1, mat_2], mat_3, flag="strict"))

# Example 3
mat__1 = np.array([[1, 2, 3]])
mat__2 = np.array([[4, 5, 6]])
mat__3 = np.array([[7, 8, 9]])
print(dot_add([mat__1, mat__2], mat__3, flag="strict"))

# Example 4
A1 = np.array([[1, 2, 3], [4, 5, 6]])
B1 = np.array([[7, 8, 9, 10, 11, 12]])
C1 = np.array([[1, 2, 3], [4, 5, 6]])
print(dot_add([A1, B1], C1, flag="flex"))

# Example 5
A2 = np.array([[1, 2], [3, 4]])
B2 = np.array([[5, 6, 7]])
C2 = np.array([[10, 20, 30], [40, 50, 60]])
print(dot_add([A2, B2], C2, flag="flex"))

# Example 6
A3 = np.array([[2, 4, 6]])
B3 = np.array([[1], [2], [3]])
C3 = np.array([[1, 2, 3]])
print(dot_add([A3, B3], C3, flag="flex"))

Mini Project: small practical reinforcement

In [57]:
import numpy as np

matrix = np.array([[240,190,100,0,130],[90,100,110,100,90],[205,0,50,45,220],[30,40,155,250,140],[80,75,150,160,230]])
print(f"original:{matrix}, shape{matrix.shape}")

#normalize to [0,1]
norm_matrix = np.round(matrix/255,4)
print(norm_matrix)

#increase brightness by 0.2
inc_matrix = norm_matrix + 0.2
print(inc_matrix)
print(f"increase brightness matrix: {inc_matrix}")

#clip value at 1.0
clipped_matrix = np.clip(inc_matrix,0,1)
print(f"clipped matrix: {clipped_matrix}")

#final pixel matrix
final_matrix = np.round(clipped_matrix*255)
print(f"final pixel matrix: {final_matrix.astype(np.int32)}")

#flatten the vector
flatten_vect = final_matrix.flatten()
print(f"flatten vector: {flatten_vect}")

original:[[240 190 100   0 130]
 [ 90 100 110 100  90]
 [205   0  50  45 220]
 [ 30  40 155 250 140]
 [ 80  75 150 160 230]], shape(5, 5)
[[0.9412 0.7451 0.3922 0.     0.5098]
 [0.3529 0.3922 0.4314 0.3922 0.3529]
 [0.8039 0.     0.1961 0.1765 0.8627]
 [0.1176 0.1569 0.6078 0.9804 0.549 ]
 [0.3137 0.2941 0.5882 0.6275 0.902 ]]
[[1.1412 0.9451 0.5922 0.2    0.7098]
 [0.5529 0.5922 0.6314 0.5922 0.5529]
 [1.0039 0.2    0.3961 0.3765 1.0627]
 [0.3176 0.3569 0.8078 1.1804 0.749 ]
 [0.5137 0.4941 0.7882 0.8275 1.102 ]]
increase brightness matrix: [[1.1412 0.9451 0.5922 0.2    0.7098]
 [0.5529 0.5922 0.6314 0.5922 0.5529]
 [1.0039 0.2    0.3961 0.3765 1.0627]
 [0.3176 0.3569 0.8078 1.1804 0.749 ]
 [0.5137 0.4941 0.7882 0.8275 1.102 ]]
clipped matrix: [[1.     0.9451 0.5922 0.2    0.7098]
 [0.5529 0.5922 0.6314 0.5922 0.5529]
 [1.     0.2    0.3961 0.3765 1.    ]
 [0.3176 0.3569 0.8078 1.     0.749 ]
 [0.5137 0.4941 0.7882 0.8275 1.    ]]
final pixel matrix: [[255 241 151  51 181]
 [141 151 1

PART 6:
1. Dot product vs element-wise multiply?
*   in element wise only element and scalar value are multiplied, the shape is same.
*   in dot and @ elements are multiplied and then added, shape is reduced to scalar.

2. What is the shape rule for matrix multiply?
*   always check inner dimensions ,they should be same (mxn)@(nxp).
*   outer shape should be (mxp).

3. Why broadcasting is required in ML training?
helps to perform various operation on vectors and matrix without worring about shape.

4. Two masking use-cases
*  in ml preprocessing
*  transformers

5. Why vectorization is faster than loops
Vectorization is faster because NumPy executes operations in optimized C code, where as py loops iterate through each value.