<a href="https://colab.research.google.com/github/satyamnewale/numpy-Book/blob/main/day_6%2Cday_7%2Cday_8-22Nov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

day_6-21Nov

Ufuncs are implemented in C and operate on whole arrays → huge speedup vs Python loops.

ufunc is divided into two parts Core element‑wise ufuncs and reduction ufuncs:

1. Core element‑wise ufuncs,
All assume x is an ndarray; results broadcast to shape of input.​

- np.exp(x) → computes
e
x
  for each element.​

- np.log(x) → natural log of each element (base
e
e); domain:
x
>
0
x>0 (0 gives
−∞, negatives → nan).​

- np.sqrt(x) → square root; domain:
x≥0 (negatives → complex or nan depending on dtype).​

- np.sin(x), np.tanh(x) → standard trig/hyperbolic functions element‑wise.​

- np.abs(x) → absolute value.​

- np.ceil(x), np.floor(x) → round up/down element‑wise.

  - Pitfalls:

    - np.log(0) → -inf, np.log of negative real → nan (need to clamp with eps).​

    - np.exp(large_positive) can overflow to inf (softmax issue)

2. Reduction ufuncs,
Reduction ufuncs aggregate along axes.​

- np.sum(x, axis=...) → sum.

- np.max, np.min → max/min.

- np.prod → product.

- np.mean → mean.

They support axis, keepdims, dtype, out etc., and are crucial for normalizations, softmax denominators, losses.

In [ ]:
#component-wise ufuncs
import numpy as np

x= np.array([2.0, -1 , 3.5, -4., 0, 0.1 , 4.1])

exp = np.exp(x)
log = np.log(x)
sqrt = np.sqrt(x)
sin = np.sin(x)
abs = np.abs(x)
ceil = np.ceil(x)
floor = np.floor(x)
cos = np.cos(x)
tan = np.tan(x)
print(f"exp : {exp}, base:{exp.base} \n")
print(f"log : {log}, base:{log.base} \n")
print(f"sqrt : {sqrt}, base:{sqrt.base} \n")
print(f"sin : {sin}, base:{sin.base} \n")
print(f"abs : {abs}, base:{abs.base} \n")
print(f"ceil : {ceil}, base:{ceil.base} \n")
print(f"floor : {floor}, base:{floor.base} \n")
print(f"cos : {cos}, base:{cos.base} \n")
print(f"tan : {tan}, base:{tan.base} \n")

#sqrt gave error due to value -1
#log of negative gives nan.

exp : [7.38905610e+00 3.67879441e-01 3.31154520e+01 1.83156389e-02
 1.00000000e+00 1.10517092e+00 6.03402876e+01], base:None 

log : [ 0.69314718         nan  1.25276297         nan        -inf -2.30258509
  1.41098697], base:None 

sqrt : [1.41421356        nan 1.87082869        nan 0.         0.31622777
 2.02484567], base:None 

sin : [ 0.90929743 -0.84147098 -0.35078323  0.7568025   0.          0.09983342
 -0.81827711], base:None 

abs : [2.  1.  3.5 4.  0.  0.1 4.1], base:None 

ceil : [ 2. -1.  4. -4.  0.  1.  5.], base:None 

floor : [ 2. -1.  3. -4.  0.  0.  4.], base:None 

cos : [-0.41614684  0.54030231 -0.93645669 -0.65364362  1.          0.99500417
 -0.57482395], base:None 

tan : [-2.18503986 -1.55740772  0.37458564 -1.15782128  0.          0.10033467
  1.42352648], base:None 



/tmp/ipython-input-4081877265.py:6: RuntimeWarning: divide by zero encountered in log
  log = np.log(x)
/tmp/ipython-input-4081877265.py:6: RuntimeWarning: invalid value encountered in log
  log = np.log(x)
/tmp/ipython-input-4081877265.py:7: RuntimeWarning: invalid value encountered in sqrt
  sqrt = np.sqrt(x)


In [ ]:
#reduction ufuncs

import numpy as np

a = np.arange(0,24,2).reshape(3,4)
print(f"a: {a} \n")
col_mean = a.mean(axis=0, keepdims=True) # shape (1, features)
row_max = a.max(axis=1, keepdims=True)   # shape (batch, 1)
print(f"col_mean : {col_mean} \n")
print(f"row_max : {row_max} \n")

row_mean = a.mean(axis=1, keepdims=True)
print(f"row_mean : {row_mean} \n")

row_min = a.min(axis=1, keepdims=True)
print(f"row_min : {row_min} \n")

row_sum = a.sum(axis=1, keepdims=True)
print(f"row_sum : {row_sum} \n")

col_sum = a.sum(axis=0, keepdims=True)
print(f"col_sum : {col_sum}")

row_prod = a.prod(axis=1, keepdims=True)
print(f"row_prod : {row_prod} \n")

relu_x = np.where(a > 5, a, 0.0)
print(f"relu_x : {relu_x} , base:{relu_x.base} \n")

clamped_low = np.where(a < 10, 10, a)
print(f"clamped_low : {clamped_low}, base:{clamped_low.base} \n")

a: [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]] 

col_mean : [[ 8. 10. 12. 14.]] 

row_max : [[ 6]
 [14]
 [22]] 

row_mean : [[ 3.]
 [11.]
 [19.]] 

row_min : [[ 0]
 [ 8]
 [16]] 

row_sum : [[12]
 [44]
 [76]] 

col_sum : [[24 30 36 42]]
row_prod : [[     0]
 [ 13440]
 [126720]] 

relu_x : [[ 0.  0.  0.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]] , base:None 

clamped_low : [[10 10 10 10]
 [10 10 12 14]
 [16 18 20 22]], base:None 



np.where and np.clip for conditional logic and clamping
---
1. np.where as vectorized if‑else:

  - np.where(condition, x, y) picks from x where condition is True, else from y, broadcasting all three:

    - Conceptual syntax: out = np.where(condition, value_if_true, value_if_false)


2. np.clip(x, a_min, a_max) clamps each element to the interval [a_min, a_max].​

 -  Values < a_min become a_min.

 -  Values > a_max become a_max.

In [ ]:
import numpy as np

A = np.array([12, 14, 13, 1500, 14, 13, 16, 15, 14, 40])

s = A.std().reshape(1,)
m = A.mean().reshape(1,)
med = np.median(A).reshape(1,)

print(f"a: {A} \n")
print(f"s: {s} \n")
print(f"m: {m} \n")
print(f"med: {med} \n")

mask = np.abs(A - m) > 2 * s
print(mask)

x_fixed = np.where(mask, med, A)
print(x_fixed)

a: [  12   14   13 1500   14   13   16   15   14   40] 

s: [445.03605472] 

m: [165.1] 

med: [14.] 

[False False False  True False False False False False False]
[12. 14. 13. 14. 14. 13. 16. 15. 14. 40.]


In [ ]:
import numpy as np

pixels = np.array([[-20, 50, 120],
                   [260, 500, 180]])

clipped_pixels = np.clip(pixels, 0, 255)

print(clipped_pixels)


In [ ]:
#Activation functions via ufuncs (vectorized)

def relu(x):
    return np.maximum(0, x)

def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

def softmax_unstable(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x, axis = 1, keepdims = True)



 # Numerical stability: overflow, underflow, precision

1. **Overflow**: number too large in magnitude to represent; result becomes inf or -inf.​​

- Example: np.exp(1000) in float32 -> inf (can affect gradient).

2. **Underflow**: number too close to zero; result becomes 0.​

- Example: np.exp(-1000) underflows to 0.
- Pitfalls:
Probabilities become 0 → log(0) = -inf
- Loss becomes NaN.

3. **Floating**‑point precision: real numbers stored with limited bits → many reals collapse to same float; small differences can be lost .

 Numerical stability means rewriting mathematically equivalent formulas so that intermediate values stay in safe ranges and precision is preserved.

 Numerical stability = turning mathematically equivalent expressions into ones that behave correctly in floating point.

In [ ]:
#Floating-Point Precision: Floating-point numbers use finite bits (32 or 64). Many real numbers cannot be represented exactly → rounding errors.

print(0.1+0.2)

#Pitfalls:
#Subtraction of nearly-equal numbers → “catastrophic cancellation”
#Variance calculation blows up if mean is large

#Edge Cases:
#(x - x.mean()) stable
#(x**2 - (x.mean())**2) unstable

0.30000000000000004


In [ ]:
logits = [1000, 1001, 999]

def stable_softmax(logits):
    # step 1: row_max = logits.max(axis=1, keepdims=True)
    row_max = logits.max(axis=1, keepdims=True)
    # step 2: shifted = logits - row_max
    shifted = logits - row_max
    # step 3: exp_vals = np.exp(shifted)
    exp_vals = np.exp(shifted)
    # step 4: probs = exp_vals / exp_vals.sum(axis=1, keepdims=True)
    probs = exp_vals / exp_vals.sum(axis=1, keepdims=True)
    return probs

# Fix: Reshape the 1D array to a 2D array (1, N) before passing to stable_softmax
probs = stable_softmax(np.array(logits).reshape(1, -1))
print(probs)

def stable_log_softmax(logits):
    # m = logits.max(...)
    m = logits.max(axis=1, keepdims=True)
    # shifted = logits - m
    shifted = logits - m
    # lse = m + np.log(np.sum(np.exp(shifted), axis=1, keepdims=True))
    lse = m + np.log(np.sum(np.exp(shifted), axis=1, keepdims=True))
    # return logits - lse
    return logits - lse

log_probs = stable_log_softmax(np.array(logits).reshape(1, -1))
print(log_probs)

def stable_normalize(x, eps=1e-8):
    # mean = x.mean(axis=1, keepdims=True)
    mean = x.mean(axis=1, keepdims=True)
    # std = x.std(axis=1, keepdims=True)
    std = x.std(axis=1, keepdims=True)
    # return (x - mean) / (std + eps)
    return (x - mean) / (std + eps)

normalize = stable_normalize(np.array(logits).reshape(1, -1))
print(normalize)

def cross_entropy_from_logits(logits, y):
    # log_probs = stable_log_softmax(logits)
    log_probs = stable_log_softmax(logits)
    # pick = log_probs[np.arange(batch), y]
    pick = log_probs[np.arange(logits.shape[0]), y]
    # loss = -pick.mean()
    loss = -pick.mean()
    # return loss
    return loss

y = np.array([1])
loss = cross_entropy_from_logits(np.array(logits).reshape(1, -1), y)
print(loss)


[[0.24472847 0.66524096 0.09003057]]
[[-1.40760596 -0.40760596 -2.40760596]]
[[ 0.          1.22474486 -1.22474486]]
0.40760596444442854


day_7-22Nov

In [3]:
import numpy as np

x = np.array([1,2,3])   # shape (3,)
print((x[:, np.newaxis]).shape)       # shape (3,1)
x[np.newaxis, :]        # shape (1,3)
print(x,x.shape)

np.expand_dims(x, axis=0)   # shape (1,3)
np.expand_dims(x, axis=1)   # shape (3,1)


(3, 1)
[1 2 3] (3,)


In [15]:
#task 1
import numpy as np

np.random.seed(42)
batch = 64
seq_len = 120
features = 32

x = np.random.randn(batch, seq_len, features)
print(x.shape)

#Normalize per feature across BOTH batch & seq
mean = np.mean(x,axis = (0,1), keepdims = True)
std = np.std(x,axis = (0,1), keepdims = True)

x_norm_batch_seq = (x - mean)/std
print(x_norm_batch_seq.shape)

#Normalize per feature across ONLY batch
mean = x.mean(axis=0, keepdims=True)   # shape (1, seq_len, features)
std  = x.std(axis=0, keepdims=True)    # shape (1, seq_len, features)

x_norm_batch = (x - mean) / std
print(x_norm_batch.shape)

#broadcasting will work in both because it works from right to left.
# mean- (1,120,32), std- (1,120,32) right to left work

#Add a bias vector (features,) to batch (64, 120, features)
bias = np.random.randn(features)
print(bias.shape)

y = x + bias
print(y.shape)

#broadcasting will work because x = (64,120,32) ,y = ( , ,32) -> right to left

#For images (50, 64, 64, 3)
img = np.random.randn(50, 64, 64, 3)
#Multiply entire tensor by a scalar
new_img = img + 1.2 # scalar broadcasting

brightness = np.array([10, -5, 0])
new_img = img + brightness #broadcasting will work
print(new_img.shape)

# illegal broadcasting
cast = np.random.rand(120)

try:
  x + cast
except :
  print(f"x + cast will not work because \n 1. x.shape = (64,120,32) \n 2. cast.shape = (120,) \n 3. compare broadcasting: (64,120,32) and ( , ,120) \n 4. 120 != 32 ,120 -> stretch 1 so possible ,64 -> stretch 1 so possible.\n 5. one condition not followed : elem not match from right to left. ")

(64, 120, 32)
(64, 120, 32)
(64, 120, 32)
(32,)
(64, 120, 32)
(50, 64, 64, 3)
x + cast will not work because 
 1. x.shape = (64,120,32) 
 2. cast.shape = (120,) 
 3. compare broadcasting: (64,120,32) and ( , ,120) 
 4. 120 != 32 ,120 -> stretch 1 so possible ,64 -> stretch 1 so possible.
 5. one condition not followed : elem not match from right to left. 


In [25]:
# task 2

import numpy as np
np.random.seed(42)
batch = 100
seq_len = 20
embed_dim = 16

x = np.random.randn(batch, seq_len, embed_dim)
print(x.shape)

y = np.random.randint(0, 5, size=(100,))
print(y.shape)

perm = np.random.permutation(len(x))
x = x[perm]
y = y[perm]

#this ensures x[0] matches y[0]

#pick batch size:
batch_size = 16

x_batches = []
y_batches = []
num_batch = len(x) // batch_size
for i in range(num_batch):
    start = i * batch_size
    end = start + batch_size

    x_batches.append(x[start:end])
    y_batches.append(y[start:end])

print(f"x_batches: {len(x_batches)} , shape: {x_batches[0].shape}") # should be (batch_size, seq_len, embed_dim)
print(f"y_batches: {len(y_batches)} , shape: {y_batches[0].shape} ") # should be (batch_size,)

#simple check
i = 5
b = 0

print(x_batches[b][i][0][:5])   # print first 5 numbers of first timestep
print(y_batches[b][i])

#Then check the original data:
global_index = b*batch_size + i
print(x[global_index][0][:5])
print(y[global_index])


(100, 20, 16)
(100,)
x_batches: 6 , shape: (16, 20, 16)
y_batches: 6 , shape: (16,) 
[ 0.06410256 -0.14726983 -0.28948327  1.71077578  0.42602501]
4
[ 0.06410256 -0.14726983 -0.28948327  1.71077578  0.42602501]
4


day_8-22Nov

# in_place vs out_of-place
- out-of-place - operation produce new array object and assign it to new memory block.eg: b = a*2 - a unchanged, b is new array.
- in-place - the operation modifies existing array memory without allocating a new array. Example idea: a *= 2 modifies a in place.

Why it matters: out-of-place allocates memory (which costs both RAM and time to allocate + copy). In-place avoids allocation and may be much faster and reduce peak memory usage.

# View vs copy

- View: a new ndarray object that references the same memory buffer as the original but with different shape, strides, or slicing.

Example: v = a[10:20] — usually returns a view.

- Copy: a completely new array with its own data.

Example: c = a[::2].copy() or c = a[fancy_index] (fancy indexing → copy).

# np.shares_memory

Use np.shares_memory(a, b) to check if two arrays possibly share the same memory block (True means modification of one may affect the other).

# .flags

a.flags shows properties: C_CONTIGUOUS (row-major), F_CONTIGUOUS (column-major), WRITEABLE, etc. Contiguity affects speed of traversal.

# Strides & layout

- a.strides tells how many bytes to step to move along each axis.

- Contiguous arrays (C-order) are faster for many C loops; Fortran-order may be faster for column-major access patterns.

- Non-contiguous strides (resulting from transposes or some slicing) can make elementwise loops slower because memory jumps reduce cache locality.

# Vectorization

- Rewriting computation to use whole-array operations (NumPy ufuncs, BLAS-backed ops) instead of Python-level loops.

- Elementwise vectorized operations are implemented in C and often use efficient inner loops and CPU features (SIMD). Linear algebra routines can call BLAS/LAPACK which are highly optimized.

- This is helpful to optimise GPU/CPU.

---
edge case:

 Use np.add(a, b, out=a) or np.multiply(a, 2, out=a) to avoid temporaries. This is often safe and efficient.

 a = (a + b) * (c - d) can create multiple temporaries. Break into steps using out= or in-place updates to reduce allocations.

In [26]:
import numpy as np
a = np.arange(10)
v = a[2:7]          # view
v[0] = 999          # a[2] is now 999
c = a[[2,4,6]]      # fancy indexing -> copy
print(f"c:{c}, base: {c.base}")
c[0] = -1           # a unchanged
print(c)
x = np.arange(6.0)
np.multiply(x, 2, out=x)   # in-place doubling
# This avoids allocation of a fresh array

y = x.T            # transposed view (non-C-contiguous)
y_c = np.ascontiguousarray(y)  # make contiguous copy for fast ops

print(y_c.flags)

c:[999   4   6], base: None
[-1  4  6]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [45]:
# Create 10 million floats → normalize → scale → clip (heavy operation.)

import numpy as np
import time, psutil, os

process = psutil.Process(os.getpid())
def mem(): return process.memory_info().rss / 1024**2

np.random.seed(42)
N = 10000000

a = np.random.randn(N)
print(a.shape,a.dtype)

print("Before:", mem())

t0 = time.time()

#normalize:
mean = a.mean()
std = a.std()
a_norm = (a - mean) / std
print(a_norm)

#scale:
a_scaled = a_norm * 1.2

#clip
a_clipped = np.clip(a_scaled, -1, 1)
print(a_clipped)

t1 = time.time()

print("After:", mem())
print("Elapsed:", t1 - t0)

(10000000,) float64
Before: 736.015625
[ 0.49677136 -0.13819847  0.6477437  ...  1.46700064  0.64446342
  0.92366338]
[ 0.59612564 -0.16583816  0.77729244 ...  1.          0.77335611
  1.        ]
After: 774.1640625
Elapsed: 0.22082281112670898


In [47]:
#optimised way
import numpy as np
import time, psutil, os

process = psutil.Process(os.getpid())
def mem(): return process.memory_info().rss / 1024**2

np.random.seed(42)

a1 = np.empty(N, dtype=np.float32)
a1 = np.random.randn(10000000).astype(a1.dtype, copy=False)
print(a1.shape,a1.dtype)

print("Before:", mem())

t0 = time.time()

#normalize:
mean = a1.mean()
std = a1.std()

np.subtract(a1, mean, out=a1) # now a holds a - mean
np.divide(a1, std, out=a1) # now a holds normalized values
np.multiply(a1, 1.2, out=a1) # in-place scaling
np.clip(a1, -1, 1, out=a1) # in-place clipping

print(a1)

t1 = time.time()

print("After:", mem())
print("Elapsed:", t1 - t0)

(10000000,) float32
Before: 850.4609375
[ 0.59612584 -0.16583821  0.7772928  ...  1.          0.77335644
  1.        ]
After: 850.4609375
Elapsed: 0.05406355857849121


In [48]:
#more optimised way
import numpy as np
import time, psutil, os

process = psutil.Process(os.getpid())
def mem(): return process.memory_info().rss / 1024**2

np.random.seed(42)

a2 = np.empty(N, dtype=np.float32)
a2 = np.random.randn(10000000).astype(a2.dtype, copy=False)
print(a2.shape,a2.dtype)

print("Before:", mem())

t0 = time.time()

#normalize:
mean = a2.mean()
std = a2.std()

a2 -= mean
a2 /= std
a2 *= 1.2
np.clip(a2, -1, 1, out=a2)

print(a2)

t1 = time.time()

print("After:", mem())
print("Elapsed:", t1 - t0)

(10000000,) float32
Before: 812.3125
[ 0.59612584 -0.16583821  0.7772928  ...  1.          0.77335644
  1.        ]
After: 812.3125
Elapsed: 0.054196834564208984


Python loop vs list-comprehension vs NumPy vectorized: timing recipe and expected differences

In [56]:
import time

N = 10000000

t01 = time.time()
#Python loop
y1 = []
for xi in range(N):
    y1.append(2*xi + 3)

t11 = time.time()
print(f"elapsed 1: {t11-t01}")

t02 = time.time()
#list-comprehension
y2 = [2*xi + 3 for xi in range(N)]

t12 = time.time()
print(f"elapsed 2: {t12-t02}")

t03 = time.time()
#NumPy vectorized
y3 = 2*np.arange(N) + 3

t13 = time.time()
print(f"elapsed 3: {t13-t03}")

print(y1==y2==y3)

elapsed 1: 1.5675709247589111
elapsed 2: 1.0534443855285645
elapsed 3: 0.041155099868774414
[ True  True  True ...  True  True  True]


# Expected results (order of magnitude)

- Python loop (pure for) is typically much slower because every element touched by Python interpreter: expect multiple orders of magnitude slower for large N.

- List comprehension is faster than for loop because it’s implemented in C loops for list construction, but still elementwise Python arithmetic overhead exists.

- NumPy vectorized operations (2 * x + 3) will usually be 10× to 100× (or more) faster than list comprehension for large arrays, depending on hardware, dtype, and operation complexity. For heavy BLAS-backed operations (matrix multiply) speedups can be even larger because highly optimized multi-threaded BLAS is used.

In [65]:
import numpy as np

# Create a random RGB image
img = np.random.rand(5,3).astype(np.float32)

print(img.shape)  # (128, 128, 3)
print(img.dtype)  # uint8

U, S, VT = np.linalg.svd(img, full_matrices=False)
print(U.shape,S.shape,VT.shape)

k = 3

S_k = np.diag(S[:k])
U_k = U[:, :k]
VT_k = VT[:k, :]

print(S_k.shape,U_k.shape,VT_k.shape)

img_approx = U_k @ S_k @ VT_k
print(img_approx.shape)

img_centered = img - np.mean(img, axis=0)

# 2. Covariance
cov = np.cov(img_centered, rowvar=False) # rowvar=False -> columns are features

# 3. Eigen decomposition
eigvals, eigvecs = np.linalg.eigh(cov)  # use eigh because cov is symmetric

# 4. Sort eigenvectors by decreasing eigenvalues
idx = np.argsort(eigvals)[::-1]
eigvals = eigvals[idx]
eigvecs = eigvecs[:, idx]

print(eigvals, eigvecs)

# 5. Project
img_proj = img_centered @ eigvecs[:, :k]
print(img_proj)

(5, 3)
float32
(5, 3) (3,) (3, 3)
(3, 3) (5, 3) (3, 3)
(5, 3)
[0.126599   0.05859047 0.00599779] [[-0.7376957  -0.66101127 -0.13736504]
 [-0.6100853   0.56553883  0.55494302]
 [ 0.28913833 -0.49318347  0.82046882]]
[[ 0.10524312 -0.30412869  0.03588952]
 [-0.3592992  -0.09077504  0.0629198 ]
 [ 0.55346905  0.13309621  0.02377278]
 [-0.23651631  0.33294493  0.011736  ]
 [-0.06289676 -0.07113769 -0.13431798]]


In [66]:
import numpy as np

# Example system
A = np.array([[2, 1],
              [1, 3]])
b = np.array([8, 13])

# Solve square system
x = np.linalg.solve(A, b)
print("Solution (solve):", x)

# Overdetermined system
A2 = np.array([[1, 1],
               [1, 2],
               [1, 3]])
b2 = np.array([6, 0, 0])
x_ls, residuals, rank, s = np.linalg.lstsq(A2, b2, rcond=None)
print("Solution (least squares):", x_ls)
print("Residuals:", residuals)


Solution (solve): [2.2 3.6]
Solution (least squares): [ 8. -3.]
Residuals: [6.]
