<a href="https://colab.research.google.com/github/satyamnewale/numpy-Book/blob/main/day_4-19Nov%2Cday_5-20Nov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
day4_19Nov

axis = 0 VS axis = 1 on shape (n_sampke, n_features)
---
Axis meaning on (n_samples, n_features)


1. In ML, a typical dataset matrix
X has shape
(n
samples
 ,n
features
 ), meaning each row is one sample and each column is one feature.​

- Row = sample: features for one training example.​

- Column = feature: same measurement across all samples.​

2. NumPy’s axis parameter says which dimension you are collapsing over:

- axis=0 → collapse down rows, compute per‑column / per‑feature statistics.​

- axis=1 → collapse across columns, compute per‑row / per‑sample statistics.​

3. For a 2D array X.shape == (n_samples, n_features):

- X.sum(axis=0) → shape
(
n
features
,
)
 one value per column/feature.​

- X.sum(axis=1) → shape
(
n
samples
,
) one value per row/sample.

In [ ]:
import numpy as np

X = np.array([
    [1, 2, 3],   # row 0
    [4, 5, 6],   # row 1
    [7, 8, 9],   # row 2
    [10,11,12],  # row 3
])  # shape (4,3)

print("---------------------------------------------------------------------")
sum_axis_none = np.sum(X, axis=None, keepdims=False)
mean_axis_none = np.mean(X, axis=None, keepdims=False)
min_axis_none = np.min(X, axis=None, keepdims=False)
max_axis_none = np.max(X, axis=None, keepdims=False)

print(f"axis = none - sum of axis with none : {sum_axis_none}, shape: {sum_axis_none.shape} ") # scalar shape
print(f"axis = none - mean of axis with none : {mean_axis_none}, shape: {mean_axis_none.shape} ") # scalar shape
print(f"axis = none - min of axis with none : {min_axis_none}, shape: {min_axis_none.shape} ") # scalar shape
print(f"axis = none - max of axis with none : {sum_axis_none}, shape: {max_axis_none.shape} ") # scalar shape

print("---------------------------------------------------------------------")
# down the row - column wise - with no keepdims
sum_axis_0 = np.sum(X, axis=0, keepdims=False)
mean_axis_0 = np.mean(X, axis=0, keepdims=False)
min_axis_0 = np.min(X, axis=0, keepdims=False)
max_axis_0 = np.max(X, axis=0, keepdims=False)

print(f"axis = 0 - sum of axis with 0 : {sum_axis_0}, shape: {sum_axis_0.shape} ") # vector output
print(f"axis = 0 - mean of axis with 0 : {mean_axis_0}, shape: {mean_axis_0.shape} ") # vector output
print(f"axis = 0 - min of axis with 0 : {min_axis_0}, shape: {min_axis_0.shape} ") # vector output
print(f"axis = 0 - max of axis with 0 : {sum_axis_0}, shape: {max_axis_0.shape} ") # vector output

print("---------------------------------------------------------------------")
#side the row - row wise - with no keepdims
sum_axis_1 = np.sum(X, axis=1, keepdims=False)
mean_axis_1 = np.mean(X, axis=1, keepdims=False)
min_axis_1 = np.min(X,axis=1,keepdims=False)
max_axis_1 = np.max(X, axis=1, keepdims=False)

print(f"axis = 1 - sum of axis with 1 : {sum_axis_1}, shape: {sum_axis_1.shape} ") # vector shape
print(f"axis = 1 - mean of axis with 1 : {mean_axis_1}, shape: {mean_axis_1.shape} ") # vector shape
print(f"axis = 1 - min of axis with 1 : {min_axis_1}, shape: {min_axis_1.shape} ") # vector shape
print(f"axis = 1 - max of axis with 1 : {sum_axis_1}, shape: {max_axis_1.shape} ") # vector shape

print("---------------------------------------------------------------------")
# down the row - column wise - with keepdims
sum_axis_0_dims = np.sum(X, axis=0, keepdims=True) #2D matrix as output
mean_axis_0_dims = np.mean(X, axis=0, keepdims=True) #2D matrix as output
min_axis_0_dims = np.min(X, axis=0, keepdims=True) #2D matrix as output
max_axis_0_dims = np.max(X, axis=0, keepdims=True) #2D matrix as output

print(f"axis = 0 - sum of axis with 0 with dims: {sum_axis_0_dims}, shape: {sum_axis_0_dims.shape} ") # matrix output
print(f"axis = 0 - mean of axis with 0 with dims: {mean_axis_0_dims}, shape: {mean_axis_0_dims.shape} ") # matrix output
print(f"axis = 0 - min of axis with 0 with dims: {min_axis_0_dims}, shape: {min_axis_0_dims.shape} ") # matrix output
print(f"axis = 0 - max of axis with 0 with dims: {sum_axis_0_dims}, shape: {max_axis_0_dims.shape} ") # matrix output

print("---------------------------------------------------------------------")
#side the row - row wise - with keepdims
sum_axis_1_dims = np.sum(X, axis=1, keepdims=True) #2D matrix as output
mean_axis_1_dims = np.mean(X, axis=1, keepdims=True) #2D matrix as output
min_axis_1_dims = np.min(X,axis=1,keepdims=True) #2D matrix as output
max_axis_1_dims = np.max(X, axis=1, keepdims=True) #2D matrix as output

print(f"axis = 1 - sum of axis with 1 with dims: {sum_axis_1_dims}, shape: {sum_axis_1_dims.shape} ") # matrix shape
print(f"axis = 1 - mean of axis with 1 with dims: {mean_axis_1_dims}, shape: {mean_axis_1_dims.shape} ") # matrix shape
print(f"axis = 1 - min of axis with 1 with dims: {min_axis_1_dims}, shape: {min_axis_1_dims.shape} ") # matrix shape
print(f"axis = 1 - max of axis with 1 with dims: {sum_axis_1_dims}, shape: {max_axis_1_dims.shape} ") # matrix shape

print("---------------------------------------------------------------------")

axis = none - sum of axis with none : 78, shape: () 
axis = none - mean of axis with none : 6.5, shape: () 
axis = none - min of axis with none : 1, shape: () 
axis = none - max of axis with none : 78, shape: () 
---------------------------------------------------------------------
axis = 0 - sum of axis with 0 : [22 26 30], shape: (3,) 
axis = 0 - mean of axis with 0 : [5.5 6.5 7.5], shape: (3,) 
axis = 0 - min of axis with 0 : [1 2 3], shape: (3,) 
axis = 0 - max of axis with 0 : [22 26 30], shape: (3,) 
---------------------------------------------------------------------
axis = 1 - sum of axis with 1 : [ 6 15 24 33], shape: (4,) 
axis = 1 - mean of axis with 1 : [ 2.  5.  8. 11.], shape: (4,) 
axis = 1 - min of axis with 1 : [ 1  4  7 10], shape: (4,) 
axis = 1 - max of axis with 1 : [ 6 15 24 33], shape: (4,) 
---------------------------------------------------------------------
axis = 0 - sum of axis with 0 with dims: [[22 26 30]], shape: (1, 3) 
axis = 0 - mean of axis with 0 wi

1. What keepdims=True actually does
- Formal definition: keepdims=True keeps reduced axes in the result as length‑1 dimensions, instead of removing them.

2. Why keepdims matters for normalization
In normalization, you usually:

- Compute statistics (mean, std, or norm) over rows or columns.​

- Subtract/divide those statistics from the original matrix X.​

3. For broadcasting to work easily:

- For row‑wise normalization (per sample): want stats of shape (n_samples, 1) so they stretch across features.​

- For column‑wise normalization (per feature): want stats of shape (1, n_features) so they stretch down rows.​

keepdims=True gives exactly these shapes directly.​

Without keepdims, you’d get 1D shapes (n_samples,) or (n_features,), which sometimes broadcast as you want but sometimes cause confusion, especially when mixing with other operations or higher‑dimensional data.​

Pitfall: omit keepdims and you get row_norms.shape == (n_samples,). This still broadcasts, but you lose the clear “column vector” geometry, and some later code expecting 2D may break.

---
Broadcasting row/column stats back to matrix
---
- Broadcasting rule (intuitive): if you try to operate on arrays with shapes that differ, NumPy will “stretch” dimensions of size 1 to match the other side, dimension by dimension from the end.​

1. For a 2D X.shape == (n_samples, n_features):

- If row_stats.shape == (n_samples, 1), then X - row_stats subtracts per row, same value across columns.​

- If col_stats.shape == (1, n_features), then X - col_stats subtracts per column, same value across rows.​

That’s exactly why keepdims=True is so nice

In [ ]:
import numpy as np

X = np.array([
    [1, 2, 3],   # row 0
    [4, 5, 6],   # row 1
    [7, 8, 9],   # row 2
    [10,11,12],  # row 3
])  # shape (4,3)

mean_axis_0 = np.mean(X, axis=0, keepdims=False)
mean_axis_1 = np.mean(X, axis=1, keepdims=False)
mean_axis_0_dims = np.mean(X, axis=0, keepdims=True) #2D matrix as output
mean_axis_1_dims = np.mean(X, axis=1, keepdims=True) #2D matrix as output

print(f"axis = 0 - mean of axis with 0 : {mean_axis_0}, shape: {mean_axis_0.shape} ") # vector output
print(f"axis = 1 - mean of axis with 1 : {mean_axis_1}, shape: {mean_axis_1.shape} ") # vector shape
print(f"axis = 0 - mean of axis with 0 with dims: {mean_axis_0_dims}, shape: {mean_axis_0_dims.shape} ") # matrix output
print(f"axis = 1 - mean of axis with 1 with dims: {mean_axis_1_dims}, shape: {mean_axis_1_dims.shape} ") # matrix shape

#when keepdim is true the true shape is never loss even if the reduction happens it preserves its shape , whereas when kept false the shape will be reduced to 1D matrix (vector).

axis = 0 - mean of axis with 0 : [5.5 6.5 7.5], shape: (3,) 
axis = 1 - mean of axis with 1 : [ 2.  5.  8. 11.], shape: (4,) 
axis = 0 - mean of axis with 0 with dims: [[5.5 6.5 7.5]], shape: (1, 3) 
axis = 1 - mean of axis with 1 with dims: [[ 2.]
 [ 5.]
 [ 8.]
 [11.]], shape: (4, 1) 


In [ ]:
import numpy as np

X = np.arange(1,25,2).reshape(3,4)

row_norms = np.linalg.norm(X, ord=2, axis=1, keepdims=False)
row_norms_dims = np.linalg.norm(X, ord=2, axis=1, keepdims=True)

col_norms = np.linalg.norm(X, ord=2, axis=0, keepdims=False)
col_norms_dims = np.linalg.norm(X, ord=2, axis=0, keepdims=True)

print(f"row normalisation order=2 ,axis=1 ,dimensions kept: {row_norms_dims}, shape: {row_norms_dims.shape}.")
print(f"row normalisation order=2 ,axis=1 ,dimensions not kept: {row_norms}, shape: {row_norms.shape}.")

print(f"col normalisation order=2 ,axis=1 ,dimensions kept: {col_norms_dims}, shape: {col_norms_dims.shape}.")
print(f"col normalisation order=2 ,axis=1 ,dimensions not kept: {col_norms}, shape: {col_norms.shape}.")

#when dimensions are not reduced ,broadcasting becomes difficult as few time broadcasting rules dont work on vectors properly.

#normalising:
try:
   norm_row = X/row_norms
   print(norm_row)
except:
  print("X/row_norms fails ((3,4)/(3,) != broadcasting):due to dimesin reduction and conversion of matrix to vector it became 1D vector. while broadcasting due to vector shape missmatch and rule violation; it fails.")

try:
   norm_col = X/col_norms
   print(f"norm_col: {norm_col}, this works due to broadcasting rule was satisfied.")
except:
   print("X/col_norms fails :due to dimesin reduction and conversion of matrix to vector it became 1D vector. while broadcasting due to vector shape missmatch and rule violation it fails.")
norm_row_dims = X/row_norms_dims
norm_col_dims = X/col_norms_dims

print(norm_row_dims, norm_col_dims)


row normalisation order=2 ,axis=1 ,dimensions kept: [[ 9.16515139]
 [24.41311123]
 [40.24922359]], shape: (3, 1).
row normalisation order=2 ,axis=1 ,dimensions not kept: [ 9.16515139 24.41311123 40.24922359], shape: (3,).
col normalisation order=2 ,axis=1 ,dimensions kept: [[19.26136028 22.15851981 25.19920634 28.33725463]], shape: (1, 4).
col normalisation order=2 ,axis=1 ,dimensions not kept: [19.26136028 22.15851981 25.19920634 28.33725463], shape: (4,).
X/row_norms fails ((3,4)/(3,) != broadcasting):due to dimesin reduction and conversion of matrix to vector it became 1D vector. while broadcasting due to vector shape missmatch and rule violation it fails.
norm_col: [[0.05191741 0.1353881  0.19841895 0.24702464]
 [0.46725672 0.49642305 0.51588926 0.5293385 ]
 [0.88259602 0.857458   0.83335958 0.81165237]], this works due to broadcasting rule was satisfied.
[[0.10910895 0.32732684 0.54554473 0.76376262]
 [0.36865436 0.45057756 0.53250075 0.61442394]
 [0.4223684  0.4720588  0.52174919

In [ ]:
import numpy as np

#norm mean/std
X = np.array([
    [1, 2, 3],   # row 0
    [4, 5, 6],   # row 1
    [7, 8, 9],   # row 2
    [10,11,12],  # row 3
])  # shape (4,3)

# column wise
col_means_dims = X.mean(axis=0, keepdims=True)    # shape (1, n_features)
col_stds_dims  = X.std(axis=0, keepdims=True)     # shape (1, n_features)

#row wise
row_means_dims = X.mean(axis=1, keepdims=True)    # shape (n_sample, 1)
row_stds_dims  = X.std(axis=1, keepdims=True)     # shape (n_sample, 1)

# column wise no keepdims true
col_means = X.mean(axis=0, keepdims=False)    # shape (n_features, )
col_stds  = X.std(axis=0, keepdims=False)     # shape (n_features, )

#row wise no keepdims true
row_means = X.mean(axis=1, keepdims=False)    # shape (n_sample, )
row_stds  = X.std(axis=1, keepdims=False)     # shape (n_sample, )

#norm
norm_cols_dim = (X - col_means_dims)/col_stds_dims
print(f"normalisation with axis=0 and keepdims=True: {norm_cols_dim}")

#norm without dims = True
norm_cols = (X - col_means)/col_stds
print(f"normalisation with axis=0 and keepdims=False: {norm_cols}")

# output tells: How many standard deviations away from the mean each original value is.

normalisation with axis=0 and keepdims=True: [[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]
normalisation with axis=0 and keepdims=False: [[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]


When you want to ensure shapes match nicely for:

- matrix equations
- avoiding shape collapse
- preventing mistakes during broadcasting
- writing neural-network code where shapes must be explicit
- keeping dimensions for later concatenations

---
Shape diagrams (in words)
---
For row‑wise mean subtraction on X.shape == (4,3):

1. Original: X → (4,3).​

2. Reduce: row_means = X.mean(axis=1, keepdims=True) → (4,1).​

3. Broadcast: X_centered = X - row_means → (4,3) again.​

For column‑wise mean subtraction:

1. X → (4,3).​

2. col_means = X.mean(axis=0, keepdims=True) → (1,3).​

3. X_centered = X - col_means → (4,3).​



---
Stacking vs concatenation vs split (2D focus)

Now for the dataset thinking on
(
n
samples
,
n
features
).

Definitions:

- np.concatenate((a, b), axis=k) → join arrays along existing axis k.​

- np.hstack((a, b)) → concatenate along columns for 2D (i.e., axis=1).​

- np.vstack((a, b)) → concatenate along rows (i.e., axis=0).​

- np.stack((a, b), axis=k) → create a new axis and stack arrays along it.​

Key mental notes you asked to write:

- “stack adds a new axis, concatenate extends an existing axis.”​

- “vstack → more rows (samples); hstack → more columns (features).”

---

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

#hstack:- concatenate along column
hstack = np.hstack([a,b])
print(f"hstack: {hstack}, shape: {hstack.shape}, expected : [1,2,3,4,5,6]")

#vstack:- concatenate along row
vstack = np.vstack([a,b])
print(f"vstack: {vstack}, shape: {vstack.shape}, expected : [[1,2,3],[4,5,6]]")

#stack:- axis = 0 along row
stack_0 = np.stack([a,b], axis=0)
print(f"stack_0: {stack_0}, shape: {stack_0.shape}, expected : [[1,2,3],[4,5,6]]")
#vstack and stack at axis = 0 are same for two 1D vectors.

#stack- axis = 1 along column
stack_1 = np.stack([a,b], axis=1)
print(f"stack_2: {stack_1}, shape: {stack_1.shape}, expected : [[1,4],[2,5],[3,6]]")
#in stack at axis = 1 , while creating new axis is added.

hstack: [1 2 3 4 5 6], shape: (6,), expected : [1,2,3,4,5,6]
vstack: [[1 2 3]
 [4 5 6]], shape: (2, 3), expected : [[1,2,3],[4,5,6]]
stack_0: [[1 2 3]
 [4 5 6]], shape: (2, 3), expected : [[1,2,3],[4,5,6]]
stack_2: [[1 4]
 [2 5]
 [3 6]], shape: (3, 2), expected : [[1,4],[2,5],[3,6]]


In [ ]:
# for two 2D matrix

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

#hstack: concatenate along col
hstack = np.hstack([a,b])
print(f"hastck: {hstack}, shape: {hstack.shape}, expected : [[1,2,5,6],[3,4,7,8]]")

#vstack: concatenate along row
vstack = np.vstack([a,b])
print(f"vstack: {vstack}, shape: {vstack.shape}, expected : [[1,2],[3,4],[5,6],[7,8]]")

#stack- axis = 0 along row
stack_0 = np.stack([a,b], axis = 0)
print(f"stack_0: {stack_0}, shape: {stack_0.shape}, expected : [[[1,2],[3,4]],[[5,6],[7,8]]]")
#stack_0 create dimension for each seperate matrix then concatenate in another dimension and together push in another dimension.

#stack- axis = 1 along col
stack_1 = np.stack([a,b], axis = 1)
print(f"stack_1: {stack_1}, shape: {stack_1.shape}, expected : [[[1,2],[5,6]],[[3,4],[7,8]]]")
#stack_1 create dimension for each seperate matrix then concatenate in another dimension below it and together push in another dimension.

hastck: [[1 2 5 6]
 [3 4 7 8]], shape: (2, 4), expected : [[1,2,5,6],[3,4,7,8]]
vstack: [[1 2]
 [3 4]
 [5 6]
 [7 8]], shape: (4, 2), expected : [[1,2],[3,4],[5,6],[7,8]]
stack_0: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape: (2, 2, 2), expected : [[[1,2],[3,4]],[[5,6],[7,8]]]
stack_1: [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]], shape: (2, 2, 2), expected : [[[1,2],[5,6]],[[3,4],[7,8]]]


vstack and hstack for datasets
---

 Vertical stacking (vstack): combine more samples.
---

1. Requirements: arrays must have same number of columns (features).​

2. Example scenario: you have X_train_part1 and X_train_part2 (two splits with same features).

3. If X_original is (5,3) and X_new is (5,2), X_with_new_features is (5,5)

4. Pitfall: shapes mismatch:

  - Trying np.vstack((X1, X2)) when X1.shape == (3,3) and X2.shape == (3,4) → error because columns differ.​

  - Trying np.hstack((X1, X2)) when row counts differ → error.

.....................................................................................................................................

 Horizontal stacking (hstack): add new features (columns).
---
1. Requirements: arrays must have same number of rows (samples).​

2. Example scenario: you engineered new features X_new with same number of samples.

np.concatenate vs hstack/vstack
---
np.concatenate is more general; hstack/vstack are convenience wrappers:

- np.hstack((a, b)) ≈ np.concatenate((a, b), axis=1) for 2D arrays.​

- np.vstack((a, b)) ≈ np.concatenate((a, b), axis=0) for 2D arrays.​

vsplit vs hsplit vs split
1. 1D array
   - hsplit is done vertically, so when queued it goes horizontally side by side.
   - vsplit is not valid for 1D array as it required more than 2 rows.
   - split :-
     - 1D = you can split only along axis 0.
     - Axis 1 does NOT exist.

2. 2D array
   - hsplit is possible.
   - vsplit is possible.
   - split -
     - both axis = 0 and axis = 1 is possible.

---

Splitting: np.split, hsplit, vsplit
---
1. For 2D datasets:

- np.vsplit(a, indices_or_sections) → split along rows (samples).​

- np.hsplit(a, indices_or_sections) → split along columns (features).​

- np.split(a, indices_or_sections, axis=k) → generic version.​

2. Features + labels split

- If data.shape == (5,4) like before, you can do:

- Use slicing: X = data[:, :3], y = data[:, 3].​

- Or use hsplit: X, y = np.hsplit(data, [3]), so X.shape == (5,3), y.shape == (5,1).​

Train/test split manually

---

In [ ]:
import numpy as np

a = np.array([1,2,3,4])

# 1D vector
#hsplit :- hsplit, NumPy treats 1D arrays as row vectors.So it automatically promotes (4,) → (1,4) internally.
hsplit = np.hsplit(a,2)
print(f"hsplit 1D: {hsplit}, expected : [1,2],[3,4]")

#vsplit : vsplit is not applicable on 1D vectors which has only one row.

#split:- works only along axis = 0 ,axis=0 refers to the only dimension
split_0 = np.split(a,2,axis = 0)
print(f"split 1D: {split_0}, expected : [1,2],[3,4]")


#2D matrix
# edge case
b = np.array([[1],[2],[3],[4]])

#hsplit : hsplit will now work because it has only one column whereas it requires more than 1 column (4,1).

#vsplit:
vsplit = np.vsplit(b,4)
print(f"vsplit 2D: {vsplit}, expected : [[[1]],[[2]],[[3]],[[4]] , where each split is a 2D shape")
print(f"shape of each vsplit: {vsplit[0].shape}, {vsplit[1].shape}, {vsplit[2].shape}, {vsplit[3].shape}, which is 2D shaped.")

#split:- axis - 0 will work as its (4,1) matrix , 4 rows can be split to 2.
split_0_b = np.split(b,2,axis = 0)
print(f"split_0_b :{split_0_b}, explected : [[[1]],[[2]],[[3]],[[4]] , where each split is a 2D shape")

#split:- axis - 1 will not work as its (4,1) matrix , 1 col cannot be split to 2.


# edge case
c = np.array([[1,2,3,4]])

#hsplit : works with axis = 1 (col)
hsplit_edge = np.hsplit(c,4)
print(f"hsplit 2D: {hsplit_edge}, expected : [[[1]],[[2]],[[3]],[[4]] , where each split is a 2D shape")
print(f"shape of each hsplit: {hsplit_edge[0].shape}, {hsplit_edge[1].shape}, {hsplit_edge[2].shape}, {hsplit_edge[3].shape}, which is 2D shaped.")

#vsplit: vsplit will now work because it has only one row whereas it requires more than 1 row (1,4).

#split:- axis - 1 will work as its (1,4) matrix , 4 col can be split to 1.
split_1_c = np.split(c,2,axis = 1)
print(f"split_0_b :{split_1_c}, explected : [[[1],[2]],[[3],[4]] , where each split is a 2D shape")
print(f"sHape of split: {split_1_c[0].shape}, {split_1_c[1].shape}")
#split:- axis - 0 will not work as its (1,4) matrix , 1 rows cannot be split to 2.


#2d matrix (4,3)
d = X = np.array([
    [1., 2., 3.],
    [4., 5., 6.],
    [7., 8., 9.],
    [10.,11.,12.],
]).astype(np.int32)

#hsplit
hsplit_2D = np.hsplit(d,3) # shall split along col
print(f"hsplit 2D: {hsplit_2D}")

#vsplit
vsplit_2D = np.vsplit(d,4) # shall split along row
print(f"vsplit 2D: {vsplit_2D}")

#split axis:0 row-wise
split_0_2D = np.split(d,4,axis = 0) # shall split along row
print(f"split_0_2D: {split_0_2D}")

#split axis:1 col-wise
split_1_2D = np.split(d,3,axis = 1) # shall split along col
print(f"split_1_2D: {split_1_2D}")


hsplit 1D: [array([1, 2]), array([3, 4])], expected : [1,2],[3,4]
split 1D: [array([1, 2]), array([3, 4])], expected : [1,2],[3,4]
vsplit 2D: [array([[1]]), array([[2]]), array([[3]]), array([[4]])], expected : [[[1]],[[2]],[[3]],[[4]] , where each split is a 2D shape
shape of each vsplit: (1, 1), (1, 1), (1, 1), (1, 1), which is 2D shaped.
split_0_b :[array([[1],
       [2]]), array([[3],
       [4]])], explected : [[[1]],[[2]],[[3]],[[4]] , where each split is a 2D shape
hsplit 2D: [array([[1]]), array([[2]]), array([[3]]), array([[4]])], expected : [[[1]],[[2]],[[3]],[[4]] , where each split is a 2D shape
shape of each hsplit: (1, 1), (1, 1), (1, 1), (1, 1), which is 2D shaped.
split_0_b :[array([[1, 2]]), array([[3, 4]])], explected : [[[1],[2]],[[3],[4]] , where each split is a 2D shape
sHape of split: (1, 2), (1, 2)
hsplit 2D: [array([[ 1],
       [ 4],
       [ 7],
       [10]], dtype=int32), array([[ 2],
       [ 5],
       [ 8],
       [11]], dtype=int32), array([[ 3],
       

Because hsplit, vsplit, dsplit always assume at least 2D:

1. hsplit → split column-wise (axis=1)

2. vsplit → split row-wise (axis=0)

3. dsplit → split depth-wise (axis=2)

For 1D input:

1. hsplit & vsplit temporarily reshape it to 2D

2. split does NOT reshape → strict axis check

- hsplit = axis:1 col
- vsplit = axis:0 row

In [ ]:
data = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 0],
    [10,11,12,1],
    [13,14,15,0],
])

#([sample sample sample | label])

X = data[:, :3]    # first 3 columns
y = data[:, 3, np.newaxis]    # last column, preserving 2D shape (n_samples, 1)
# Alternatively, y = data[:, 3, np.newaxis]

print(f"X: {X}, shape: {X.shape}")
print(f"y: {y}, shape: {y.shape}")
X_train = X[:3]
X_test  = X[3:]
y_train = y[:3]
y_test  = y[3:]

print(f"X_train: {X_train}, shape: {X_train.shape}")
print(f"X_test: {X_test}, shape: {X_test.shape}")
print(f"y_train: {y_train}, shape: {y_train.shape}")
print(f"y_test: {y_test}, shape: {y_test.shape}")

X: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]], shape: (5, 3)
y: [[0]
 [1]
 [0]
 [1]
 [0]], shape: (5, 1)
X_train: [[1 2 3]
 [4 5 6]
 [7 8 9]], shape: (3, 3)
X_test: [[10 11 12]
 [13 14 15]], shape: (2, 3)
y_train: [[0]
 [1]
 [0]], shape: (3, 1)
y_test: [[1]
 [0]], shape: (2, 1)


In [ ]:
X1 = np.array([[1,2,3],[4,5,6]])     # shape (2,3)
X2 = np.array([[7,8,9]])             # shape (1,3)
y1 = np.array([0, 1])
y2 = np.array([1])

X_all = np.concatenate((X1, X2), axis = 0)   # vstack or concatenate axis=0
y_all = np.concatenate((y1, y2), axis = 0)   # hstack or concatenate axis=0
print(X_all)
print(y_all)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 1 1]


X side:

X1 = (2,3) and X2 = (1,3)
→ same number of columns → can concatenate along axis=0
→ vstack works
→ concatenate(axis=0) works

y side:

y1 = (2,) and y2 = (1,)
→ 1D so only axis=0 exists
→ hstack = concatenate along the only axis → works

| Function              | Works on  | Requirement                      | Meaning                      |
| --------------------- | --------- | -------------------------------- | ---------------------------- |
| `concatenate(axis=0)` | 1D/2D     | same **columns**                 | join rows                    |
| `concatenate(axis=1)` | 2D        | same **rows**                    | join columns                 |
| `vstack`              | 1D→2D, 2D | same **columns**                 | vertical (row) stacking      |
| `hstack`              | 1D or 2D  | 1D → trivial, 2D → same **rows** | horizontal (column) stacking |


In [ ]:
X_basic = np.array([
    [1., 2.],
    [3., 4.],
    [5., 6.],
])  # shape (3,2)

X_extra = np.array([
    [10.],
    [20.],
    [30.],
])  # shape (3,1)

X_full = np.hstack((X_basic, X_extra))  # which stacking?
print(X_full.shape)


(3, 3)


---

day5_20NOv

In [ ]:
import numpy as np

rng = np.random.default_rng(42)
uniform_samples = rng.random((10,3)) # shape (10,3): 10 samples, 3 features
print(f"uniform samples: {uniform_samples}")

normal_sample = rng.normal(loc=0.0, scale=1.0, size=(10,3))
print(normal_sample)

int_sample = rng.integers(0, 10, size=5)
print(int_sample)

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]
 [0.45038594 0.37079802 0.92676499]
 [0.64386512 0.82276161 0.4434142 ]
 [0.22723872 0.55458479 0.06381726]
 [0.82763117 0.6316644  0.75808774]
 [0.35452597 0.97069802 0.89312112]
 [0.7783835  0.19463871 0.466721  ]
 [0.04380377 0.15428949 0.68304895]]
[[ 2.1416476  -0.40641502 -0.51224273]
 [-0.81377273  0.61597942  1.12897229]
 [-0.11394746 -0.84015648 -0.82448122]
 [ 0.65059279  0.74325417  0.54315427]
 [-0.66550971  0.23216132  0.11668581]
 [ 0.2186886   0.87142878  0.22359555]
 [ 0.67891356  0.06757907  0.2891194 ]
 [ 0.63128823 -1.45715582 -0.31967122]
 [-0.47037265 -0.63887785 -0.27514225]
 [ 1.49494131 -0.86583112  0.96827835]]
[8 5 0 7 5]


In [ ]:
import numpy as np

np.random.seed(42)
uniform_sample = np.random.rand(10,3) # shape (10,3): 10samples, 3 features
print(uniform_sample)

normal_sample = np.random.randn(10,3)
print(normal_sample)

int_sample = np.random.randint(0, 10, size=5)
print(int_sample)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041]]
[[-1.15099358  0.37569802 -0.60063869]
 [-0.29169375 -0.60170661  1.85227818]
 [-0.01349722 -1.05771093  0.82254491]
 [-1.22084365  0.2088636  -1.95967012]
 [-1.32818605  0.19686124  0.73846658]
 [ 0.17136828 -0.11564828 -0.3011037 ]
 [-1.47852199 -0.71984421 -0.46063877]
 [ 1.05712223  0.34361829 -1.76304016]
 [ 0.32408397 -0.38508228 -0.676922  ]
 [ 0.61167629  1.03099952  0.93128012]]
[0 4 9 6 9]


Contrast: uniform vs normal
---
1. Uniform: all values in interval equally likely; histogram looks flat.​

2. Normal: bell‑shaped; most values around mean, tails rare; good for weights or noise.

---
Normal/Gaussian random
---
1. rng.normal(loc=0.0, scale=1.0, size=...) or np.random.randn(...) → samples from Normal(mean=loc, std=scale).​

2. Default is standard normal
N
(
0
,
1
)
N(0,1).

---
Uniform random (continuous)
---
1. rng.random(size) or np.random.rand(...) → samples from Uniform(0, 1): any value between 0 and 1 is equally likely.

---

1. Uniform Sampling — np.random.rand()

Uniform sampling means every value in a range is equally likely.

Range: 0 to 1 (inclusive of 0, exclusive of 1)

- Properties
  - Mean ≈ 0.5
  - All values between 0 and 1 are equally common.
  - No negative numbers ever.

- To change range
  - Example: range [-1, 1]
  - 2 * np.random.rand() - 1

---
2. Gaussian Sampling — np.random.randn()

Gaussian = Normal distribution = bell-curve shaped distribution.

- np.random.randn() uses:
  - Mean (μ) = 0
  - Standard deviation (σ) = 1

- Range: technically (-∞, +∞)
  - but practically:
  - 95% values lie between -2 and +2
  - 99.7% lie between -3 and +3

- Example: may give: 1.12, -0.44, 2.9, etc.

- Properties :
  - Values cluster around 0
  - Negative values common
  - Extreme values possible but rare

- To change mean & variance
  - Gaussian with mean μ and std σ: μ + σ * np.random.randn()
  - ex: 5 + 2 * np.random.randn()

In [12]:
import numpy as np

rng = np.random.default_rng(42)

x = rng.random((10,3))
print(x)

y = rng.integers(0, 10, size=(10,))
print(y)

indices = rng.permutation(len(x))
print(indices)

x_shuffled = x[indices]
y_shuffled = y[indices]

print("Shuffled x:\n", x_shuffled)
print("Shuffled y:\n", y_shuffled)

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]
 [0.45038594 0.37079802 0.92676499]
 [0.64386512 0.82276161 0.4434142 ]
 [0.22723872 0.55458479 0.06381726]
 [0.82763117 0.6316644  0.75808774]
 [0.35452597 0.97069802 0.89312112]
 [0.7783835  0.19463871 0.466721  ]
 [0.04380377 0.15428949 0.68304895]]
[9 7 3 9 4 3 9 3 0 4]
[2 7 5 3 8 4 1 9 6 0]
Shuffled x:
 [[0.7611397  0.78606431 0.12811363]
 [0.35452597 0.97069802 0.89312112]
 [0.22723872 0.55458479 0.06381726]
 [0.45038594 0.37079802 0.92676499]
 [0.7783835  0.19463871 0.466721  ]
 [0.64386512 0.82276161 0.4434142 ]
 [0.69736803 0.09417735 0.97562235]
 [0.04380377 0.15428949 0.68304895]
 [0.82763117 0.6316644  0.75808774]
 [0.77395605 0.43887844 0.85859792]]
Shuffled y:
 [3 3 3 9 0 4 7 4 9 9]


In [15]:
import numpy as np

np.random.seed
x = np.random.rand(10, 3)
print(x)
y = np.random.randint(0, 10, size = 10)
print(y)

indices = np.random.permutation(len(x))
print(indices)
x_shuffled = x[indices]
y_shuffled = y[indices]

print("Shuffled x:\n", x_shuffled)
print("Shuffled y:\n", y_shuffled)


[[0.42200136 0.36239559 0.31218811]
 [0.91025685 0.09823054 0.40498863]
 [0.76001788 0.3033932  0.96587374]
 [0.24464538 0.86231839 0.96865454]
 [0.65498889 0.56875456 0.38537936]
 [0.1901356  0.83860548 0.95118172]
 [0.13928408 0.84610081 0.71696581]
 [0.23044406 0.13881872 0.92058622]
 [0.18351881 0.96636954 0.51727013]
 [0.0827017  0.75117815 0.27213166]]
[9 6 2 2 9 8 0 1 5 2]
[9 7 5 0 8 6 3 2 1 4]
Shuffled x:
 [[0.0827017  0.75117815 0.27213166]
 [0.23044406 0.13881872 0.92058622]
 [0.1901356  0.83860548 0.95118172]
 [0.42200136 0.36239559 0.31218811]
 [0.18351881 0.96636954 0.51727013]
 [0.13928408 0.84610081 0.71696581]
 [0.24464538 0.86231839 0.96865454]
 [0.76001788 0.3033932  0.96587374]
 [0.91025685 0.09823054 0.40498863]
 [0.65498889 0.56875456 0.38537936]]
Shuffled y:
 [2 1 8 9 5 0 2 2 6 9]
10


Shuffling, permutation, and paired permutation
---
2. shuffle vs permutation
- Two key tools:

  - rng.shuffle(x) or np.random.shuffle(x)

  - In‑place shuffle along first axis: original array is modified.​

  - For 2D x → shuffles rows (axis 0) by default.​

- rng.permutation(x) or np.random.permutation(x)

  - Returns a shuffled copy, does not modify original.​

  - If x is an integer n, returns a shuffled np.arange(n)

---
Why shuffling y with x is important?
---

consider x = samples; y = labels;
- if you shuffle only x it will not match true values ( resulting labels ) in y.
- this will lead to error while training the model and after-wards it will predict wrong outputs.
---

indexing for 2D is according to row-wise.

In [28]:
import numpy as np

rng = np.random.default_rng(42)

x = rng.random((10,3))
print(x)

y = rng.integers(0, 10, size=(10,))
print(y)

perm = np.random.permutation(len(x))

x_shuffled = x[perm]
y_shuffled = y[perm]

batch_size = 4

batch_idx = perm[:batch_size]
print(f"{batch_idx} \n")
x_batch = x_shuffled[batch_idx]  # shape (batch_size, n_features)
y_batch = y_shuffled[batch_idx]  # shape (batch_size,)

print(x_batch, y_batch)

n = x.shape[0]
for start in range(0, n, batch_size):
    end = start + batch_size
    batch_idx = perm[start:end]    # slice of the index array
    x_batch = x[batch_idx]
    y_batch = y[batch_idx]
    # ... use this mini-batch
print(f"\n {x_batch}, {y_batch}")
print(f"\n x_batch size: {x_batch.size}, y_batch size: {y_batch.size}")

idx = [1, 3, 7]
x_selected = x[idx]
y_selected = y[idx]

print(f"x selected :{x_selected}, shape: {x_selected.shape}, strides: {x_selected.strides}, type: {x_selected.flags}, view or copy: {x_selected.base} : none means copy.")
print(f"y selected :{y_selected}, shape: {y_selected.shape}, strides: {y_selected.strides}, type: {y_selected.flags}, view or copy: {y_selected.base} : none means copy.")

mask1 = x[:, 0] > 0.25     # shape (n,)
mask2 = x[:, 0] > 0.25    # shape (n,)
x_pos = x[mask1]           # all rows where first feature > 0
y_pos = y[mask2]           # corresponding labels
print(f"x_pos: {x_pos},  strides: {x_pos.strides}, type: {x_pos.flags}, view or copy: {x_pos.base} : none means copy.")
print(f"y_pos: {y_pos},  strides: {y_pos.strides}, type: {y_pos.flags}, view or copy: {y_pos.base} : none means copy.")

for start in range(0, n, batch_size):
    end = start + batch_size
    batch_idx = rng.choice(n, size=batch_size, replace=True)
    x_batch = x[batch_idx]
    y_batch = y[batch_idx]
    # ... use this mini-batch
print(f"\n {x_batch}, {y_batch}")
print(f"\n x_batch size: {x_batch.size}, y_batch size: {y_batch.size}")



[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]
 [0.45038594 0.37079802 0.92676499]
 [0.64386512 0.82276161 0.4434142 ]
 [0.22723872 0.55458479 0.06381726]
 [0.82763117 0.6316644  0.75808774]
 [0.35452597 0.97069802 0.89312112]
 [0.7783835  0.19463871 0.466721  ]
 [0.04380377 0.15428949 0.68304895]]
[9 7 3 9 4 3 9 3 0 4]
[8 3 9 5] 

[[0.7611397  0.78606431 0.12811363]
 [0.22723872 0.55458479 0.06381726]
 [0.64386512 0.82276161 0.4434142 ]
 [0.69736803 0.09417735 0.97562235]] [3 3 4 7]

 [[0.7611397  0.78606431 0.12811363]
 [0.64386512 0.82276161 0.4434142 ]], [3 4]

 x_batch size: 6, y_batch size: 2
x selected :[[0.69736803 0.09417735 0.97562235]
 [0.45038594 0.37079802 0.92676499]
 [0.35452597 0.97069802 0.89312112]], shape: (3, 3), strides: (24, 8), type:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
, view or copy: None : none means copy.
y select

C‑order vs F‑order
---

-  C‑order (row‑major): default in NumPy.​

   - Elements in the same row are stored next to each other in memory.

   - Last index varies fastest.

- F‑order (column‑major): Fortran style.​

  - Elements in the same column are adjacent.

  - First index varies fastest.

Conceptual picture for a 2×3 array [[a, b, c], [d, e, f]]:
---
- C‑order memory: [a, b, c, d, e, f].

- F‑order memory: [a, d, b, e, c, f]