<a href="https://colab.research.google.com/github/satyamnewale/numpy-Book/blob/main/day_1-14Dev.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day 1 - 14 Nov

In [33]:
#create an array
import numpy as np

arr = np.array([1,2,3,4,5]) #[5,]
print(f"array shape :{arr.shape}, array dimension: {arr.ndim}, size: {arr.size}, dtype : {arr.dtype}, itemsize :{arr.itemsize}")

arr1= np.arange(0,10,2) #[0,2,4,6,8]
# arange(start,end,gap)
print(f"array shape :{arr1.shape}, array dimension: {arr1.ndim}, size: {arr1.size}, dtype : {arr1.dtype}, itemsize :{arr1.itemsize}, array:{arr1}")

arr2= np.linspace(1,5,5)
print(f"linspace: {arr2}, {arr2.dtype}")

arr_zero =np.zeros([3,3])
print(f"zeros: {arr_zero}, {arr_zero.dtype}")

arr_ones =np.ones([3,2])
print(f"ones: {arr_ones},{arr_ones.dtype}")

arr_full= np.full([3,3],5)
print(f"fully: {arr_full},{arr_full.dtype}")

arr_eye = np.eye(3,2) # can create non square matrix and has "k" which shift diagnols
print(f"arr_eye:{arr_eye},{arr_eye.dtype}")

arr_identity = np.identity(3)
print(f"arr_identity:{arr_identity},{arr_identity.dtype}")

#dtype conversion :
arr_int = np.array([1,2,3,4,5])
print(f"{arr_int},{arr_int.dtype}")

arr_float = arr_int.astype(np.float64)
print(f"{arr_float},{arr_float.dtype}")

# view and copy
arr_main = np.array([2,4,5,6,8])
arr_view = arr_main.view()
arr_view[0] = 99
print(f"arr_main: {arr_main},arr_view: {arr_view}") # view shares same memory and when changed, original array also changes.
print(f"arr_main id: {id(arr_main)}, arr_view id: {id(arr_view)}") #data object is different
print(f"arr_view base:{arr_view.base}") # gives main array

arr_copy = arr_main.copy()
arr_copy[0] = 9
print(f"arr_main: {arr_main},arr_copy: {arr_copy}") # copy does not share same memory and when changed, original array dont change.
print(f"arr_main id: {id(arr_main)}, arr_copy id: {id(arr_copy)}") #data object is different
print(f"arr_copy base:{arr_copy.base}") # gives main array

#slicing
arr_slice = np.array([1,2,3,4,5,6,7])
print(f"arr_slice:{arr_slice}")

print(f"arr_slice[1:5]:{arr_slice[1:5]}")
print(f"arr_slice[4:]:{arr_slice[4:]}")
print(f"arr_slice[:4]:{arr_slice[:4]}")
print(f"arr_slice[-3:-1]:{arr_slice[-3:-1]}")
print(f"arr_slice[1:5:2]:{arr_slice[1:5:2]}")
print(f"arr_slice[::2]:{arr_slice[::2]}")

arr_slice_2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(f"arr_slice_2d:{arr_slice_2d}")
print(f"arr_slice_2d[1,1:4]:{arr_slice_2d[1,1:4]}")
print(f"arr_slice_2d[0:2,0:2]:{arr_slice_2d[0:2,0:2]}")

#flatten and reshape
arr_main_reshape = np.array([[1,2,3,7],[4,5,6,2],[7,8,9,1]])
arr_flatten = arr_main_reshape.flatten()
print(f"arr_main:{arr_main_reshape}")
print(f"arr_flatten:{arr_flatten}")

print(f"arr_main_reshape.reshape(4,3):{arr_main_reshape.reshape(4,3)},shape :{arr_main_reshape.reshape(4,3).shape}, dim: {arr_main_reshape.reshape(4,3).ndim}")
print(f"arr_main_reshape.reshape(2,2,3):{arr_main_reshape.reshape(2,2,3)},shape:{arr_main_reshape.reshape(2,2,3).shape}, dim:{arr_main_reshape.reshape(2,2,3).ndim}")
print(f"arr_main_reshape.reshape(2,2,-1):{arr_main_reshape.reshape(2,2,-1)},shape:{arr_main_reshape.reshape(2,2,-1).shape}, dim:{arr_main_reshape.reshape(2,2,-1).ndim}")
print(f"arr_flatten.reshape(6,2):{arr_flatten.reshape(6,2)}, shape:{arr_flatten.reshape(6,2).shape}, dim:{arr_flatten.reshape(6,2).ndim}")

array shape :(5,), array dimension: 1, size: 5, dtype : int64, itemsize :8
array shape :(5,), array dimension: 1, size: 5, dtype : int64, itemsize :8, array:[0 2 4 6 8]
[1. 2. 3. 4. 5.], float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], float64
[[1. 1.]
 [1. 1.]
 [1. 1.]],float64
[[5 5 5]
 [5 5 5]
 [5 5 5]],int64
arr_eye:[[1. 0.]
 [0. 1.]
 [0. 0.]],float64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]],float64
[1 2 3 4 5],int64
[1. 2. 3. 4. 5.],float64
arr_main: [99  4  5  6  8],arr_view: [99  4  5  6  8]
arr_main id: 134787693734544, arr_view id: 134787694119024
arr_view base:[99  4  5  6  8]
arr_main: [99  4  5  6  8],arr_copy: [9 4 5 6 8]
arr_main id: 134787693734544, arr_copy id: 134787693627984
arr_copy base:None
arr_slice:[1 2 3 4 5 6 7]
arr_slice[1:5]:[2 3 4 5]
arr_slice[4:]:[5 6 7]
arr_slice[:4]:[1 2 3 4]
arr_slice[-3:-1]:[5 6]
arr_slice[1:5:2]:[2 4]
arr_slice[::2]:[1 3 5 7]
arr_slice_2d:[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
arr_slice_2d[1,1:4]:[7 8 9]
arr_slice_2d[0:2,0:2]:

task

In [35]:
#create an array of shape (3,),(3,3),(3,4,2) manually
arr1D = np.array([1,2,3])
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3D = np.array([[[1,2],[3,4],[5,6],[7,8]],[[8,7],[6,5],[4,3],[2,1]],[[2,4],[6,8],[1,3],[5,7]]])

print(f"arr1D: {arr1D}, shape: {arr1D.shape}, dim: {arr1D.ndim}")
print(f"arr2D: {arr2D}, shape: {arr2D.shape}, dim: {arr2D.ndim}")
print(f"arr3D: {arr3D}, shape: {arr3D.shape}, dim: {arr3D.ndim}")

#type changing
print(f"arr2D.astype(np.float64): {arr2D.astype(np.float64)}, rechange: {arr2D.astype(np.float64).astype(np.int64)}")

# copy
a = np.array([1,2,3])
b = a
c = a.copy()

b[0]= 9
c[2]= 9

print(f"a: {a}, b: {b}, this is a view and when view changed original arr also changes")
print(f"a: {a}, c: {c}, this is a copy and when copy is changed the changes are made in copy only because it dont share same memory with original arr.")

#create evenly spaced vector
vec = np.linspace(0,10,2)
print(f"evenly spaced vector : {vec}")

#make identical matrix and modify it
iden_arr = np.identity(3)
print(f"iden_arr: {iden_arr}")

#modify diagnoal
modify_add = 3 + iden_arr
print(f"modify_add: {modify_add.astype(np.int64)}")

modify_sub = 3 - iden_arr
print(f"modify_sub: {modify_sub.astype(np.int64)}")

mofify_mul = 3 * iden_arr
print(f"modify_mul: {mofify_mul.astype(np.int64)}")

arr1D: [1 2 3], shape: (3,), dim: 1
arr2D: [[1 2 3]
 [4 5 6]
 [7 8 9]], shape: (3, 3), dim: 2
arr3D: [[[1 2]
  [3 4]
  [5 6]
  [7 8]]

 [[8 7]
  [6 5]
  [4 3]
  [2 1]]

 [[2 4]
  [6 8]
  [1 3]
  [5 7]]], shape: (3, 4, 2), dim: 3
arr2D.astype(np.float64): [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], rechange: [[1 2 3]
 [4 5 6]
 [7 8 9]]
a: [9 2 3], b: [9 2 3], this is a view and when view changed original arr also changes
a: [9 2 3], c: [1 2 9], this is a copy and when copy is changed the changes are made in copy only because it dont share same memory with original arr.
evenly spaced vector : [ 0. 10.]
iden_arr: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
modify_add: [[4 3 3]
 [3 4 3]
 [3 3 4]]
modify_sub: [[2 3 3]
 [3 2 3]
 [3 3 2]]
modify_mul: [[3 0 0]
 [0 3 0]
 [0 0 3]]


mini project

In [3]:
import numpy as np

main_arr = input("enter array here :")
datatype = input("enter dtype to convert: ")
arr_format = np.array(eval(main_arr))

def check_func(arr1,datatype = "none"):
  arr = arr1.astype(np.int32)

  if(datatype != "none"):
    arr_change_dtype = arr.astype(datatype)

  shape = arr.shape
  ndim = arr.ndim
  dtype = arr.dtype
  itemsize = arr.itemsize
  size = arr.size

  flatten_arr = arr.flatten()
  value = f"original array: {arr}, changed dtype array: {arr_change_dtype}, shape: {shape}, ndim: {ndim}, dtype: {dtype}, itemsize: {itemsize}, size: {size}, flatten array: {flatten_arr}"
  return value

print(check_func(arr_format,datatype))

enter array here :[1,2,3,4]
enter dtype to convert: int64
enter dtype to convert: 2,2
array: [1 2 3 4], shape: (4,), ndim: 1, dtype: int64, itemsize: 8, size: 4, flatten array: [1 2 3 4]
